package io.github.shazaanashraff.apiforge.modules.executor;

import io.github.shazaanashraff.apiforge.shared.BaseEntity;
import jakarta.persistence.*;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A single HTTP request + expected assertions, belonging to a test run.
 *
 * <p>Generated by the test category generators (S07). Executed by the executor (S10).
 * The category enum must stay in sync with TestCategory in the testgenerator module.
 *
 * <p>request_headers, request_query_params, request_path_params, and expected_assertions
 * are stored as JSONB in Postgres for flexible schema.
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "test_cases")
public class TestCase extends BaseEntity {

  @Column(name = "tenant_id", nullable = false)
  private UUID tenantId;

  @Column(name = "test_run_id", nullable = false)
  private UUID testRunId;

  @Column(name = "category", nullable = false, length = 30)
  private String category;

  @Column(name = "endpoint_path", nullable = false, length = 500)
  private String endpointPath;

  @Column(name = "http_method", nullable = false, length = 10)
  private String httpMethod;

  @Column(name = "description", columnDefinition = "TEXT")
  private String description;

  @Column(name = "request_headers", columnDefinition = "jsonb")
  private String requestHeaders;

  @Column(name = "request_query_params", columnDefinition = "jsonb")
  private String requestQueryParams;

  @Column(name = "request_path_params", columnDefinition = "jsonb")
  private String requestPathParams;

  @Column(name = "request_body", columnDefinition = "TEXT")
  private String requestBody;

  @Column(name = "expected_assertions", columnDefinition = "jsonb")
  private String expectedAssertions;

  /** True for MongoDB-specific tests that only apply when the project flag is set. */
  @Column(name = "applicable_if_mongo", nullable = false)
  private boolean applicableIfMongo = false;
}
